# Runs tests and deploys to dev stage
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.21.0

      - name: Setup Node and Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type Check
        run: npm run type-check

      - name: Unit Tests
        run: pnpm test:unity

      - name: Create Artifact
        run: pnpm sls package --package pack

      - name: Zip artifact
        run: zip -r pack.zip pack

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: serverless-artifact
          path: pack.zip

  deploy-development:
    name: Deploy dev
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.21.0

      - name: Setup Node and Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: actions/download-artifact@v3

      - name: Zip artifact
        run: unzip pack.zip -d ..
        working-directory: serverless-artifact

      - name: serverless deploy
        uses: serverless/github-action@v3.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: deploy --stage dev --package pack

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action